### ISSUE TITLE
Wondering if it would be possible to provide filled quantity in openOrders

### ISSUE THREAD

**Issue by srijanshetty** [bitbns-official/node-bitbns-api#17]
It's a standard practice of exchanges to provide filled quantity in openOrders, could you kindly do the same!

**Comment by srijanshetty** [comment]
@atiprashant could you kindly look into this issue?

**Comment by atiprashant** [comment]
Right now we have filled amount in checkStatus api. We will bring it in open orders soon

**Comment by Nisthar** [comment]
@atiprashant is it added now?
