### ISSUE TITLE
No memo in getCoinAddress for BNB address

### ISSUE THREAD

**Issue by Wicpar** [bitbns-official/node-bitbns-api#19]
Hi,

Your api returns no memo for BNB deposit addresses, and thus I incurred a BNB loss, is it possible to recover it ? I assume all chains relying on memos instead of tags are affected.
Anyway, this bug really makes me reconsider the viability of this platform, such losses are unacceptable...

**Comment by atiprashant** [comment]
Sorted now, only BNB was missing

**Comment by sanket-buyhatke** [comment]
Hi, @Wicpar was your issue resolved ??
If you have incurred losses, could share relevant information (address and hash) ?
