### ISSUE TITLE
Add Scopes to the Write operations

### ISSUE THREAD

**Issue by fayazara** [bitbns-official/node-bitbns-api#24]
I see that there is an option to sell without any 2FA, I believe there should be scopes to disable write operations, this looks extremely unsafe.

**Comment by sanket-buyhatke** [comment]
hi @fayazara, thanks for your suggestion, 
could you please elaborate on your suggestion, we would try to integrate it soon.

**Comment by fayazara** [comment]
What I mean is, giving almost all access to a single token is not safe, if someone wants just **read access** to their account and do not to do "Sell Order" Write operation, you could give the api keys scopes.

**Comment by sanket-buyhatke** [comment]
yes, noted
thanks for the explanation, will try to implement it in the near future.
