### ISSUE TITLE
getOHLCData API not working

### ISSUE THREAD

**Issue by varsubham** [bitbns-official/node-bitbns-api#28]
getOHLCData API is producing this error message when using it:-

"status": 0,
"msg": "Invalid market or coin passed"

**Comment by sanket-buyhatke** [comment]
hi, could you please specify for which pair you are receiving this response for ?

**Comment by varsubham** [comment]
@sanket-buyhatke Its not working for any pair. For eg,.. if I am using BTC INR pair its showing the same error message

```
bitbns.getOHLCData("BTC", "INR", 0, function (error, data) {
  if (!error) {
    console.log("Data ::", data);
  } else {
    console.log("Error ::", error);
  }
});
```

Its giving the same error message:
```
Data :: { status: 0, msg: 'Invalid market or coin passed' }
```

**Comment by sanket-buyhatke** [comment]
noted, thanks for raising the issue 
will look into it

**Comment by sanket-buyhatke** [comment]
hi, @varsubham, could update to the latest version and pls try again ?

**Comment by varsubham** [comment]
Yes working fine now 👍
