### ISSUE TITLE
getOrderBookSocket only returns BTC

### ISSUE THREAD

**Issue by nitnk9** [bitbns-official/node-bitbns-api#29]
I've tried using different coins but the getOrderBookSocket always returns BTC trades.

UPDATE: The object key is 'btc' the prices and trades do change according to the coin.

**Comment by sanket-buyhatke** [comment]
rite,
 
```
{ btc: 1600, rate: 3045981.54, time: '2021-05-25T03:49:25.726Z' },
{ btc: 1309, rate: 3045981.54, time: '2021-05-25T03:48:55.725Z' },
{ btc: 1900, rate: 3045981.53, time: '2021-05-25T03:48:55.711Z' },
{ btc: 2710, rate: 3045674.91, time: '2021-05-25T03:48:05.688Z' },
```

btc here refers to volume and rate refers to current rate.
