### ISSUE TITLE
API modification

### ISSUE THREAD

**Issue by metal32** [bitbns-official/node-bitbns-api#3]
Guys! Is it possible to merge GET buyOrderBook and sellOrderBook API for a coin into one, as it will reduce the number of requests that we will have to hit to fetch data, and will certainly reduce the server load on your side too?

**Comment by atiprashant** [comment]
You can directly use the sockets now for but orders , sell orders and trade history, all of them together

**Comment by keshav-iitr** [comment]
Hi, I have been trying the  private rest APIs from Android device but I always get 403 in error code. Can anyone help here?
