### ISSUE TITLE
BuyOrderBook Get API Issue

### ISSUE THREAD

**Issue by metal32** [bitbns-official/node-bitbns-api#4]
While hitting the buyOrderBook get API for coin - "SIA", API: 'https://api.bitbns.com/api/trade/v1/orderbook/buy/SIA'
I'm getting this response: {"data":"","status":0,"msg":"coin name not supplied"}

While for coin - "PHX", API: 'https://api.bitbns.com/api/trade/v1/orderbook/buy/PHX'
I'm getting this response: {"status":0,"error":null}

Please help me

**Comment by atiprashant** [comment]
Please use SC and RPX respectively for those coins.
