### ISSUE TITLE
API v2 is not working

### ISSUE THREAD

**Issue by ghost** [bitbns-official/node-bitbns-api#6]
The **getOrders** functionality is not working.

The code taken from the examples in readme does not work.

`bitbns.getOrders({
	side : 'usdtListOpenOrders',
	symbol : 'TRX_USDT',
	page : 0
}, function(error, data) {
	console.log(data)
});`

The response that is returned from the server is as below.
`{"msg":"Invalid Type","status":-1}`

In fact, none of the USDT market related APIs are working.

**Comment by atiprashant** [comment]
It has been fixed now :)
