### ISSUE TITLE
None of the USDT pair related functionality works.

### ISSUE THREAD

**Issue by bLaNk-ghost** [bitbns-official/node-bitbns-api#8]
The getOrders functionality is not working.

The code taken from the examples in readme does not work. (even after the latest commit)

bitbns.getOrders({ side : 'usdtListOpenOrders', symbol : 'TRX_USDT', page : 0 }, function(error, data) { console.log(data) });

The response that is returned from the server is as below.
{"msg":"Something Went Wrong","status":-1}

Tried changing symbol to TRXUSDT but no success.

The above functionality is just an example. The cancelOrders, placeOrders does not work either.

**Comment by atiprashant** [comment]
Have you tried the updated code ? I will check and fix it .

**Comment by bLaNk-ghost** [comment]
It does not work even after the update.

**Comment by bLaNk-ghost** [comment]
It does not work even after the update.

**Comment by bLaNk-ghost** [comment]
It does not work even after the update.

**Comment by bLaNk-ghost** [comment]
Hi Guys. Any update on this ?

**Comment by atiprashant** [comment]
All the endpoints are sorted now

**Comment by bLaNk-ghost** [comment]
Working fine now. Great :-)
